# Numpy

In [1]:
import numpy as np

In [2]:
scalar = np.array(1)

In [3]:
print(scalar)

1


In [4]:
lst_1d = [1, 2, 3, 4, 5]
arr_1d = np.array(lst_1d)

In [5]:
print(lst_1d)
print(arr_1d)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
print(type(lst_1d))
print(type(arr_1d))

<class 'list'>
<class 'numpy.ndarray'>


# ------------------------------------

In [7]:
lst_2d = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(lst_2d)

In [8]:
print(lst_2d)
print(arr_2d)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


# ------------------------------------

In [9]:
lst_3d = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
arr_3d = np.array(lst_3d)

In [10]:
arr_4d = np.array([[[[1,2], [3, 4]]]])

In [11]:
print(lst_3d)
print("-----------")
print(arr_3d)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
-----------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [12]:
len(lst_3d)

2

In [13]:
len(arr_3d)

2

In [14]:
arr_3d.shape

(2, 3, 3)

In [15]:
arr_3d.size

18

In [16]:
arr_3d.ndim

3

In [17]:
arr_3d.dtype

dtype('int64')

In [18]:
print('type = ', arr_3d.dtype)
print('number of dimensions = ', arr_3d.ndim)
print('shape = ', arr_3d.shape)
print('size = ', arr_3d.size)
print('itemsize = ', arr_3d.itemsize, " Bytes")
print('data = ', arr_3d.data)

type =  int64
number of dimensions =  3
shape =  (2, 3, 3)
size =  18
itemsize =  8  Bytes
data =  <memory at 0x108bfa980>


In [19]:
arr_float = np.array([1,2,3], dtype= str)

In [20]:
arr_float

array(['1', '2', '3'], dtype='<U1')

In [21]:
arr_float.dtype

dtype('<U1')

In [22]:
type(arr_float[0])

numpy.str_

In [23]:
arr_float = np.array((1,2,3), dtype= str)

In [24]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [25]:
arr_2d.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr_2d = arr_2d.reshape(3, 2)

In [28]:
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
arr_2d.shape = (1, 2, 3)

In [30]:
arr_2d

array([[[1, 2, 3],
        [4, 5, 6]]])

# -------------------------------------

In [31]:
np.empty([2, 2])

array([[0., 0.],
       [0., 0.]])

In [32]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
np.full((3, 3, 3), 255)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]])

In [35]:
np.full((3, 3, 3), [255, 255, 0])

array([[[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [204]:
a = np.random.randint(10, size= (3, 3))
a

array([[4, 2, 6],
       [8, 2, 9],
       [6, 9, 8]])

In [206]:
np.multiply(a, np.eye(3))

array([[4., 0., 0.],
       [0., 2., 0.],
       [0., 0., 8.]])

In [37]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [38]:
np.linspace(0, 15, 3)

array([ 0. ,  7.5, 15. ])

In [39]:
np.random.random((3, 3))

array([[0.82730552, 0.37413804, 0.00268901],
       [0.99951296, 0.07131605, 0.68681659],
       [0.61525155, 0.86918848, 0.17776269]])

In [40]:
np.random.randint(4,5)

4

In [41]:
np.random.randint(1, 10, size=(3, 4))

array([[7, 2, 8, 2],
       [7, 7, 7, 4],
       [8, 7, 6, 7]])

# ------------------------------

In [42]:
a = np.arange(4)
b = np.arange(4, 9)
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [43]:
a = np.arange(4)
b = np.arange(4, 8)
print("a = ", a)
print("b = ", b)

a =  [0 1 2 3]
b =  [4 5 6 7]


In [44]:
np.add(a, b)

array([ 4,  6,  8, 10])

In [45]:
np.subtract(a, b)

array([-4, -4, -4, -4])

In [46]:
np.multiply(a, b)

array([ 0,  5, 12, 21])

In [47]:
np.divide(a, b)

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [48]:
np.dot(a, b)

38

## Universal Functions

In [49]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [150]:
np.log(5)

1.6094379124341003

In [144]:
np.log10(10)

1.0

In [153]:
np.exp(2)

7.38905609893065

In [155]:
np.exp2(3)

8.0

## Aggregate Functions

In [219]:
a = np.array([100, 1, 2, 3, 4, 5])
a

array([100,   1,   2,   3,   4,   5])

In [220]:
a.min()

1

In [221]:
a.max()

100

In [222]:
a.mean()

19.166666666666668

In [223]:
a.std()

36.17281053805775

In [227]:
np.sort(a)

array([  1,   2,   3,   4,   5, 100])

In [224]:
a.argmax()

0

In [225]:
a.argmin()

1

In [226]:
a.argsort()

array([1, 2, 3, 4, 5, 0])

# Indexing, Slicing

In [56]:
a = np.array([0, 1, 2, 3, 4, 5])
a

array([0, 1, 2, 3, 4, 5])

In [57]:
a[0]

0

a[1]

In [58]:
a[1:3]

array([1, 2])

In [59]:
b = np.random.randint(0, 100, size= (4, 5))
b 

array([[74, 87, 78, 54,  0],
       [24, 64, 12, 81, 21],
       [83,  4, 96, 99,  8],
       [34, 45, 33, 47, 70]])

In [60]:
b[2, 3]

99

In [61]:
b[2, 2]

96

In [62]:
b[0:3, 1:4]

array([[87, 78, 54],
       [64, 12, 81],
       [ 4, 96, 99]])

In [63]:
b[0:3:2, 1:4:2]

array([[87, 54],
       [ 4, 99]])

# Iterating

In [92]:
c = np.random.randint(1, 10, size=(12, ))
c

array([8, 9, 7, 8, 1, 7, 4, 5, 9, 3, 4, 7])

In [93]:
for i in c:
    print(i)

8
9
7
8
1
7
4
5
9
3
4
7


In [94]:
c.shape = (3, 4)
c

array([[8, 9, 7, 8],
       [1, 7, 4, 5],
       [9, 3, 4, 7]])

In [95]:
for i in c:
    for j in i:
        print(j)

8
9
7
8
1
7
4
5
9
3
4
7


# Flat very important

In [96]:
np.array(c.flat)

array([8, 9, 7, 8, 1, 7, 4, 5, 9, 3, 4, 7])

In [97]:
for i in c.flat:
    print(i)

8
9
7
8
1
7
4
5
9
3
4
7


In [98]:
for i in c.flat[:5]:
    print(i)

8
9
7
8
1


## ----------------------

In [100]:
c

array([[8, 9, 7, 8],
       [1, 7, 4, 5],
       [9, 3, 4, 7]])

In [ ]:
# 0 for col
# 1 for row

In [125]:
np.apply_along_axis(np.mean, axis=1, arr= c)

array([8.  , 4.25, 5.75])

In [126]:
def std(x):
    x = np.sum(x)
    
    if x >= 30:
        return True
    else:
        return False

In [127]:
np.apply_along_axis(std, axis=1, arr= c)

array([ True, False, False])

## Conditions and Boolean Arrays


In [235]:
a = np.random.random((4, 4))
a

array([[0.56330673, 0.4408479 , 0.45309023, 0.46063311],
       [0.53405272, 0.43394032, 0.1239646 , 0.512968  ],
       [0.93663621, 0.14416194, 0.0783045 , 0.72990426],
       [0.60614347, 0.2809762 , 0.19274539, 0.20522171]])

In [236]:
a > 0.5

array([[ True, False, False, False],
       [ True, False, False,  True],
       [ True, False, False,  True],
       [ True, False, False, False]])

In [237]:
a[a > 0.5]

array([0.56330673, 0.53405272, 0.512968  , 0.93663621, 0.72990426,
       0.60614347])

In [238]:
np.where(a > 0.5)

(array([0, 1, 1, 2, 2, 3]), array([0, 0, 3, 0, 3, 0]))

# Array Manipulation

In [161]:
a = np.zeros((3, 3))
b = np.ones((3, 3))
print(a)
print()
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [162]:
np.vstack((a, b))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [163]:
np.hstack((a, b))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [164]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [179]:
e = np.row_stack((a, b, c))
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [180]:
e = np.column_stack((a, b, c))
e

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [182]:
np.hsplit(e, 3)

[array([[0],
        [1],
        [2]]),
 array([[3],
        [4],
        [5]]),
 array([[6],
        [7],
        [8]])]

In [183]:
np.vsplit(e, 3)

[array([[0, 3, 6]]), array([[1, 4, 7]]), array([[2, 5, 8]])]

In [229]:
a = np.random.randint(10, size=(3, 6))
a

array([[8, 5, 5, 6, 6, 3],
       [8, 5, 2, 3, 3, 6],
       [3, 4, 5, 8, 8, 8]])

In [230]:
a.transpose()

array([[8, 8, 3],
       [5, 5, 4],
       [5, 2, 5],
       [6, 3, 8],
       [6, 3, 8],
       [3, 6, 8]])


# Copies or Views of Objects


In [185]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [186]:
b = a

In [187]:
print("a = ", a)
print("b = ", b)

a =  [1 3 5 7 9]
b =  [1 3 5 7 9]


In [188]:
b[2] = 10

In [189]:
print("a = ", a)
print("b = ", b)

a =  [ 1  3 10  7  9]
b =  [ 1  3 10  7  9]


In [190]:
b = a.copy()

In [191]:
print("a = ", a)
print("b = ", b)

a =  [ 1  3 10  7  9]
b =  [ 1  3 10  7  9]


In [192]:
b[2] = 100

In [193]:
print("a = ", a)
print("b = ", b)

a =  [ 1  3 10  7  9]
b =  [  1   3 100   7   9]
